// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
namespace TestV2RafCollection
{
	/// <summary>
	///This is a test class for Vevy.Collections.RafCollection&lt;T&gt;.StandardComparison and is intended
	///to contain all Vevy.Collections.RafCollection&lt;T&gt;.StandardComparison Unit Tests
	///</summary>
	[TestClass()]
	public class StandardComparisonTest
	{


		private TestContext testContextInstance;

		/// <summary>
		///Gets or sets the test context which provides
		///information about and functionality for the current test run.
		///</summary>
		public TestContext TestContext
		{
			get
			{
				return testContextInstance;
			}
			set
			{
				testContextInstance = value;
			}
		}
		#region Additional test attributes
		// 
		//You can use the following additional attributes as you write your tests:
		//
		//Use ClassInitialize to run code before running the first test in the class
		//
		//[ClassInitialize()]
		//public static void MyClassInitialize(TestContext testContext)
		//{
		//}
		//
		//Use ClassCleanup to run code after all tests in a class have run
		//
		//[ClassCleanup()]
		//public static void MyClassCleanup()
		//{
		//}
		//
		//Use TestInitialize to run code before running each test
		//
		//[TestInitialize()]
		//public void MyTestInitialize()
		//{
		//}
		//
		//Use TestCleanup to run code after each test has run
		//
		//[TestCleanup()]
		//public void MyTestCleanup()
		//{
		//}
		//
		#endregion


	}
	/// <summary>
	///This is a test class for Vevy.Collections.RafCollection&lt;T&gt;.DescriptorComparison and is intended
	///to contain all Vevy.Collections.RafCollection&lt;T&gt;.DescriptorComparison Unit Tests
	///</summary>
	[TestClass()]
	public class DescriptorComparisonTest
	{


		private TestContext testContextInstance;

		/// <summary>
		///Gets or sets the test context which provides
		///information about and functionality for the current test run.
		///</summary>
		public TestContext TestContext
		{
			get
			{
				return testContextInstance;
			}
			set
			{
				testContextInstance = value;
			}
		}
		#region Additional test attributes
		// 
		//You can use the following additional attributes as you write your tests:
		//
		//Use ClassInitialize to run code before running the first test in the class
		//
		//[ClassInitialize()]
		//public static void MyClassInitialize(TestContext testContext)
		//{
		//}
		//
		//Use ClassCleanup to run code after all tests in a class have run
		//
		//[ClassCleanup()]
		//public static void MyClassCleanup()
		//{
		//}
		//
		//Use TestInitialize to run code before running each test
		//
		//[TestInitialize()]
		//public void MyTestInitialize()
		//{
		//}
		//
		//Use TestCleanup to run code after each test has run
		//
		//[TestCleanup()]
		//public void MyTestCleanup()
		//{
		//}
		//
		#endregion


		/// <summary>
		///A test for DescriptorComparison (ListSortDescriptionCollection)
		///</summary>
		[TestMethod()]
		public void ConstructorTest()
		{
			// Unit Test Generation Error: A private accessor could not be created for Vevy.Collections.RafCollection<T>.DescriptorComparison.DescriptorComparison: Unspecified error
			Assert.Fail("Unit Test Generation Error: A private accessor could not be created for Vevy.Coll" +
					"ections.RafCollection<T>.DescriptorComparison.DescriptorComparison: Unspecified " +
					"error");
		}

	}
	/// <summary>
	///This is a test class for Vevy.Collections.RafCollection&lt;T&gt;.ProxyStorageComparer and is intended
	///to contain all Vevy.Collections.RafCollection&lt;T&gt;.ProxyStorageComparer Unit Tests
	///</summary>
	[TestClass()]
	public class ProxyStorageComparerTest
	{


		private TestContext testContextInstance;

		/// <summary>
		///Gets or sets the test context which provides
		///information about and functionality for the current test run.
		///</summary>
		public TestContext TestContext
		{
			get
			{
				return testContextInstance;
			}
			set
			{
				testContextInstance = value;
			}
		}
		#region Additional test attributes
		// 
		//You can use the following additional attributes as you write your tests:
		//
		//Use ClassInitialize to run code before running the first test in the class
		//
		//[ClassInitialize()]
		//public static void MyClassInitialize(TestContext testContext)
		//{
		//}
		//
		//Use ClassCleanup to run code after all tests in a class have run
		//
		//[ClassCleanup()]
		//public static void MyClassCleanup()
		//{
		//}
		//
		//Use TestInitialize to run code before running each test
		//
		//[TestInitialize()]
		//public void MyTestInitialize()
		//{
		//}
		//
		//Use TestCleanup to run code after each test has run
		//
		//[TestCleanup()]
		//public void MyTestCleanup()
		//{
		//}
		//
		#endregion


		/// <summary>
		///A test for ProxyStorageComparer (IComparer&lt;T&gt;)
		///</summary>
		[TestMethod()]
		public void ConstructorTest()
		{
			// Unit Test Generation Error: A private accessor could not be created for Vevy.Collections.RafCollection<T>.ProxyStorageComparer.ProxyStorageComparer: Unspecified error
			Assert.Fail("Unit Test Generation Error: A private accessor could not be created for Vevy.Coll" +
					"ections.RafCollection<T>.ProxyStorageComparer.ProxyStorageComparer: Unspecified " +
					"error");
		}

	}


}
